### ISSUE TITLE
有个地方报错呢

### ISSUE THREAD

**Issue by chaoxz1** [wu-boy/serialPort#1]
SerialPortUtils.addListener(serialPort, () -> {
            byte[] data = SerialPortUtils.read(serialPort);
            System.out.println(HexUtil.encodeHexStr(data));
        });
lambda表达式里面的serialPort报错：Variable used in lambda expression should be final or effectively final

**Comment by wu-boy** [comment]
Lambda表达式只能引用final变量（对于非final变量，该变量在既成事实上必须是final），因此不要对serialPort重复赋值，或者给serialPort变量添加final限制即可解决问题。

**Comment by chaoxz1** [comment]
谢谢。我有另外一个问题能帮我看一下吗？
在你写的这个例子里，我注释掉后边往串口写数据的代码，于是就只是接受串口传来的数据，但是在执行cn.wu.demo.serialport.util.SerialPortUtils.read(Lgnu/io/SerialPort)的时候报错。查看错误日志如下：
Java frames: (J=compiled Java code, j=interpreted, Vv=VM code)
j  gnu.io.RXTXPort.readArray([BII)I+0
j  gnu.io.RXTXPort$SerialInputStream.read([BII)I+212
j  gnu.io.RXTXPort$SerialInputStream.read([B)I+60
j  cn.wu.demo.serialport.util.SerialPortUtils.read(Lgnu/io/SerialPort;)[B+30
j  cn.wu.demo.serialport.SerialPortTest.lambda$main$0(Lgnu/io/SerialPort;)V+1
j  cn.wu.demo.serialport.SerialPortTest$$Lambda$1.dataAvailable()V+4
j  cn.wu.demo.serialport.util.SerialPortListener.serialEvent(Lgnu/io/SerialPortEvent;)V+71
j  gnu.io.RXTXPort.sendEvent(IZ)Z+382
v  ~StubRoutines::call_stub
j  gnu.io.RXTXPort.eventLoop()V+0
j  gnu.io.RXTXPort$MonitorThread.run()V+12
v  ~StubRoutines::call_stub
请问该怎么解决呢？
感激不尽。

**Comment by wu-boy** [comment]
不好意思，我也看不出来是什么原因造成的。
